feedback/urls.py
from django.conf.urls import url
from django.urls import include, path
from . import views

app_name = "feedback"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    path('submit_feedback/', views.submit_feedback, name='submit_feedback'),
]

feedback/models.py
from django.db import models

# Create your models here.
class Feedback(models.Model):
    rating = models.IntegerField(default=0)
    feedback = models.TextField(default="", blank=True)
    email = models.EmailField(default="", blank=True)
    page = models.CharField(default="/", max_length=500)
    def __str__(self):
        return "[{rating}]: {page}\t{text}".format(rating=self.rating, text=self.feedback[0:50], page=self.page)

feedback/views.py
# Create your views here.
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
import json
from random import random
import os
import datetime
from django.utils import timezone
import random
import requests
from django.conf import settings


from .models import Feedback

app_name = 'feedback'

def index(request):
    template_path = '{app}/index.html'.format(app=app_name)
    context = {}
    return render(request, template_path, context)



def submit_feedback(request):
    if request.POST:
        try:
            feedback = Feedback()
            feedback.rating = request.POST['rating']
            feedback.feedback = request.POST['feedback']
            feedback.email = request.POST['email']
            feedback.page = request.POST['page']
            feedback.save()
            print('here', request.POST, feedback)
            return HttpResponse('submitted')
        except:
            return HttpResponse('error')

    return HttpResponse('Not posted to submit_feedback.')

feedback/templates/feedback/base.html
{% load static %}
<feedback-widget-dependencies>
  <!-- Bootstrap v4 stylesheet  -->
  <link rel="stylesheet" type="text/css" href="{% static 'feedback/bootstrap/css/bootstrap.min.css' %}" />

  <!-- Bootstrap v4 has 2 dependencies, jQuery and popper  -->
  <script src="{% static 'feedback/jQuery/js/jquery-3.3.1.min.js' %}" type="text/javascript"></script>
  <!-- <script src="{% static 'core/popper/js/popper-1.13.0.js' %}" type="text/javascript"></script> -->

  <!-- Bootstrap v4 js -->
  <script src="{% static 'feedback/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>

  <!-- Font Awesome v4  -->
  <link rel="stylesheet" type="text/css" href="{% static 'feedback/font-awesome-4.7.0/css/font-awesome.min.css' %}" />


  <!-- custom style -->
  <link rel="stylesheet" type="text/css" href="{% static 'feedback/custom/css/base.css' %}" />

  {% block head %}

  {% endblock %}
</feedback-widget-dependencies>



<feedback-widget>
  {% block content %}

  {% endblock %}
</feedback-widget>

feedback/templates/feedback/feedback.html
{% extends 'feedback/base.html' %}
{% load static %}


{% block content %}
<ul class="nav nav-tabs rotate-text--90 " id="feedback-tab">
  <li type="button" class="nav-item" data-toggle="modal" data-target="#feedback-modal">
    <a class="nav-link active">Feedback</a>
  </li>
</ul>



<div class="modal fade" id="feedback-modal" tabindex="-1" role="dialog" aria-labelledby="feedback-modal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title align-middle" id="feedback-modal-label">Feedback on:</h5>
        <nav aria-label="breadcrumb"><ol class="modal-bc breadcrumb align-middle" id="feedback-breadcrumbs"></ol></nav>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <form novalidate id='feedback-form' action='{% url 'feedback:submit_feedback' %}' method='post'>
          {% csrf_token %}
          <div class="form-group">
            <label for="feedback-form-rating">Rating:</label>
            <img src="{% static 'feedback/custom/imgs/flaticon/sick.svg' %}" alt="1" class='icon '>
            <img src="{% static 'feedback/custom/imgs/flaticon/crying.svg' %}" alt="2" class='icon '>
            <img src="{% static 'feedback/custom/imgs/flaticon/sad.svg' %}" alt="3" class='icon '>
            <img src="{% static 'feedback/custom/imgs/flaticon/confused.svg' %}" alt="4" class='icon '>
            <img src="{% static 'feedback/custom/imgs/flaticon/smile.svg' %}" alt="5" class='icon '>
            <img src="{% static 'feedback/custom/imgs/flaticon/in-love.svg' %}" alt="6" class='icon '>
            <img src="{% static 'feedback/custom/imgs/flaticon/star-struck.svg' %}" alt="7" class='icon active'>
            <input type="text" name="rating" value="7" id='feedback-form-rating' style="display:none" required>
            <div class="valid-feedback">
              Looks good!
            </div>
          </div>

          <div class="form-group">
            <label for="feedback-from-text">Feedback:</label>
            <textarea class='form-control' name="feedback" rows="3" cols="80"></textarea>
          </div>


          <div class="form-group">
            <div class="form-check">
              <input class="form-check-input" type="checkbox" id="may-we-contact-you">
              <label class="form-check-label" for="may-we-contact-you">
                May we contact you?
              </label>
            </div>
          </div>

          <div class="form-group" style='display:none;' id='feedback-email-container'>
            <label for="exampleInputEmail1">Email address</label>
            <input  name="email" type="email" class="form-control" id="feedback-email" aria-describedby="email-help" placeholder="Enter email"  pattern="[^@]+@[^@]+\.[a-zA-Z]{2,6}">
            <small id="feedback-email" class="form-text text-muted">We'll never share your email with anyone else.</small>
            <div class="invalid-feedback">
              Please enter a valid email.
            </div>
          </div>


          <div class="form-group" style="display:none">
            <label for="feedback-form-page">Page:</label>
            <input type="text" name="page" value="" id='feedback-form-page' required>
          </div>

        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button id="feedback-form-submit-button" type="button" class="btn btn-primary">Submit</button>
      </div>
      <div class="">
      <small class="form-text text-muted" style='font-size: 8px'><div>Icons made by <a href="https://www.flaticon.com/authors/vectors-market" title="Kiss">Kiss</a> from <a href="https://www.flaticon.com/"     title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/"     title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div></small>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript" src="{% static 'feedback/custom/js/async-form-submission.js' %}"></script>
{% endblock %}

feedback/templates/feedback/index.html
{% load static %}
{% include 'feedback/feedback.html' %}


<div>Icons made by <a href="https://www.flaticon.com/authors/vectors-market" title="Kiss">Kiss</a> from <a href="https://www.flaticon.com/"     title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/"     title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>